#!/usr/bin/env Rscript

#####################################################
# Author: Bingxin Lu
# Description: This script is used to visualize the tree of multi-regional tumor sample generated by phylovar. The tree was generated by phylovar  from the original input tree. The top clades in the tree whose CCF (Cancer Cell Fraction) is no less than 0.2 are highlighted by different colors. Each clade correponds to a cluster in the simulated data.
# Assumption: Suppose there are 5 samples generated from the tumor population.
#####################################################


library(ggtree)
library(ape)
library(dplyr)
library(tidyr)
library(readr)
library(magrittr)
library(ggplot2)

idir="input"
odir="output"
# Suppose clones with CCF(Cancer Cell Fraction)>=ccf_cutoff can be detected 
ccf_cutoff=0.2
colors=c('#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99','#e31a1c','#fdbf6f','#ff7f00','#cab2d6','#6a3d9a','#ffff99','#b15928')
# The maximum number of clades to highlight
max_clades=10

# Read affiliation 
affiliation = read_delim(file.path(idir,"affiliation_tumopp_random.txt"), delim=" ", col_types = "cdddc")
names(affiliation) = c("sector", "purity", "depth", "prune_p", "cells")
# Find the affiliation of each node
node_size = unlist(lapply(affiliation$cells, function(x) length(strsplit(x, ",")[[1]])))
max_size = max(node_size)
affiliation %>% dplyr::select(sector, cells) %>% tidyr::separate(cells, as.character(seq(1:max_size))) %>% t() %>% as.data.frame() -> sect_cells
names(sect_cells) = sect_cells[1,]
sect_cells = sect_cells[2:nrow(sect_cells),]
sect_cells %>% tidyr::gather(key=sector, value=node) -> sect_node

# Read the tree generated by phylovar
tree = read.nhx(file.path(odir, "tree.nhx"))
# Nodes in the tree
tree_nodes = tree@data$nodeid
tree_leaves = tree@phylo$tip.label

# Read node mapping
tmap = read_tsv(file.path(odir,"tipnode_samples.map/tumor.tipnode.map"), col_types = "cic")
names(tmap) = c("tip_node", "cell_count", "tcells")
tnode_size = unlist(lapply(tmap$tcells, function(x) length(strsplit(x, ",")[[1]])))
max_size = max(tnode_size)
# Find the affiliation of current tip nodes
tmap %>% dplyr::select(tip_node, tcells) %>% tidyr::separate(tcells, as.character(seq(1:max_size))) %>% t() %>% as.data.frame() -> tip_nodes
names(tip_nodes) = tip_nodes[1,]
tip_nodes = tip_nodes[2:nrow(tip_nodes),]
# One tip may represent multiple leaves in the input tree
tip_nodes %>% tidyr::gather(key=tip, value=node) %>% na.omit() -> tip_node

# Combine affiliation and tip information
sect_tip_node = merge(sect_node, tip_node, by="node")
sect_tip_node %>% dplyr::select(sector, tip) %>% unique() -> tip_sect
# One tip node may have a parent combing nodes from different sectors
tip_sect %>% group_by(tip) %>% arrange(sector) %>% summarise(sectors = paste(sector, collapse =","), num_sector = length(sector)) %>% arrange(desc(num_sector), sectors) -> tip_sects
tip_sect %>% group_by(sector) %>% arrange(tip) %>% summarise(tips  = paste(tip, collapse =","), num_tips = length(sector)) %>% arrange(desc(num_tips), tips) -> sect_tips

# All the nodes in the tree have CCFs
tree_ccf = read_tsv(file.path(odir, "nodes_ccf.txt"))
names(tree_ccf) = c("node", "sct1", "sct2", "sct3", "sct4", "sct5", "tumor")

# Only nodes (internal or leaves) with mutations are output in nodes_vars.txt
nodes_vars = read_tsv(file.path(odir, "nodes_vars.txt"), col_types = "cciic")
names(nodes_vars) = c("node", "chr", "start", "end", "var")
node_with_vars = unique(nodes_vars$node)

# Combine affiliation, tip and clone information
tree_ccf_sects = merge(tree_ccf, tip_sects, by.x="node", by.y="tip", all.x = TRUE)
tree_ccf_sects %>% dplyr::rename(nodeid = node) %>% dplyr::mutate(sectors=replace_na(sectors, ""), num_sector=replace_na(num_sector, 0)) -> tree_ccf_sects
tree_ccf_sects$node=unlist(lapply(tree_ccf_sects$nodeid, function(x) match(x, tree@data$nodeid)))

# Find nodes in the tree that are not in nodes_vars (nodes with no mutation)
node_no_muts = setdiff(tree_nodes, node_with_vars)
# Clones that can be detected, sort by CCF
tree_ccf  %>% dplyr::filter(tumor >= ccf_cutoff) %>% dplyr::filter(!node %in% node_no_muts) %>% dplyr::arrange(desc(tumor)) -> node_detected
nids = match(node_detected$node, tree_nodes)

# Plot original tree
tree@data %<>% dplyr::mutate(nSNV=as.numeric(nSNV), nAMP=as.numeric(nAMP), nDEL=as.numeric(nDEL)) %>% dplyr::mutate(nSNV=replace_na(nSNV,0), nAMP=replace_na(nAMP,0), nDEL=replace_na(nDEL,0)) 
tree@data$muts=as.numeric(tree@data$nSNV) + as.numeric(tree@data$nAMP) + as.numeric(tree@data$nDEL)
gtree <- ggtree(tree, branch.length = 'muts', aes(color=sectors, linetype=sectors)) %<+% tree_ccf_sects + geom_nodepoint(aes(color="red", alpha=tumor, size=2.5)) + geom_text(aes(label=gsub("node", "", nodeid)), hjust=-0.2, size=3) + theme_tree2() + geom_tippoint(size=1.5) 
plot(gtree)


# Color nodes by CCFs
n_show=if(length(nids)<=max_clades) length(nids) else max_clades
for(i in 2:n_show){
  # print(tree_nodes[nids[i]])
  gtree <- gtree + geom_hilight(node=nids[i], fill=colors[i], alpha=0.2)
}
fname=file.path(odir, "clone_assign.pdf")
# Use large width to avoid incomplete tip label 
pdf(fname, width=16, height=8)
plot(gtree)
dev.off()

