#!/usr/bin/env Rscript

#####################################################
# Author: Bingxin Lu
# Description: This script is used to visualize the tree of single tumor sample generated by phylovar.
# Assumption: Suppose there are 5 samples generated from the tumor population.
#####################################################

library(ggtree)
library(dplyr)
library(tidyr)
library(readr)
library(magrittr)

# Compute the expected tree length for a coalescent ree of k leaves
get_expected_treelen <- function(k)
{
  # k=1e6
  # k=1000
  sum=0
  for(i in 2:k)
  {
    # i=10000
    x = 1/(i-1)
    a = round(x, 3)
    # print(a)
    sum = sum + a
  }
  sum = 2*sum
  # print(sum)
  return(sum)
}

# Replace NA with 0
hybrd.rplc_at.ctn <- function(x) { 
  mutate_at(x, vars(matches("nSNV|nAMP|nDEL")), funs(replace(., is.na(.), 0))) 
}

dir="output/"
# Suppose clones with CCF(Cancer Cell Fraction)>=ccf_cutoff can be detected 
ccf_cutoff=0.2
colors=c('#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99','#e31a1c','#fdbf6f','#ff7f00','#cab2d6','#6a3d9a','#ffff99','#b15928')
# The maximum number of clades to highlight
max_clades=10

# Read the tree generated by phylovar
tree = read.nhx(file.path(dir, "tree.nhx"))
# Nodes in the tree
tree_nodes = tree@data$nodeid
tree_leaves = tree@phylo$tip.label

# All the nodes in the tree have CCFs
tree_ccf = read_tsv(file.path(dir, "nodes_ccf.txt"))
names(tree_ccf) = c("nodeid", "tumor")
tree_ccf$node=unlist(lapply(tree_ccf$nodeid, function(x) match(x, tree@data$nodeid)))

# Only nodes (internal or leaves) with mutations are output in nodes_vars.txt
nodes_vars = read_tsv(file.path(dir, "nodes_vars.txt"), col_types = "cciic")
names(nodes_vars) = c("node", "chr", "start", "end", "var")
node_with_vars = unique(nodes_vars$node)

# Find the number of mutations in each tree node
nodes_vars %>% tidyr::unite(pos, chr, start, end) -> node_pos_var
node_pos_var %>% dplyr::group_by(node) %>% dplyr::summarise(total = n()) -> node_num_muts

# Find nodes in the tree that are not in nodes_vars (nodes with no mutation)
node_no_muts = setdiff(tree_nodes, node_with_vars)

# Find clones that can be detected 
tree_ccf %>% dplyr::filter(tumor >= ccf_cutoff) %>% dplyr::filter(!nodeid %in% node_no_muts) %>% dplyr::arrange(desc(tumor)) -> node_detected
nids = match(node_detected$nodeid, tree_nodes)

# Visualize the clonal tree
tree@data %<>% dplyr::mutate(nSNV=as.numeric(nSNV), nAMP=as.numeric(nAMP), nDEL=as.numeric(nDEL)) %>% dplyr::mutate(nSNV=replace_na(nSNV,0), nAMP=replace_na(nAMP,0), nDEL=replace_na(nDEL,0)) 
tree@data$muts=as.numeric(tree@data$nSNV) + as.numeric(tree@data$nAMP) + as.numeric(tree@data$nDEL)
gtree <- ggtree(tree, branch.length = 'muts') %<+% tree_ccf + geom_nodepoint(aes(color="red", alpha=tumor), size=2.5) + geom_text(aes(label=gsub("node", "", nodeid)), hjust=-.2, size=3) + theme_tree2() + geom_tippoint(size=1.5)

n_show=if(length(nids)<=max_clades) length(nids) else max_clades
for(i in 2:n_show){
  # print(tree_nodes[nids[i]])
  gtree <- gtree + geom_hilight(node=nids[i], fill=colors[i], alpha=0.2)
}
fname=file.path(dir, "clone_assign.pdf")
# Use large width to avoid incomplete tip label 
pdf(fname, width=16, height=8)
plot(gtree)
dev.off()

